library(tidyverse)
library(readxl)
library(lubridate)
###import sheet manually
usa_reg <- read_excel("D:/Google Drive/Library/Forecasting/data/reg.xlsx", sheet = "usa_reg")
china_reg <- read_excel("D:/Google Drive/Library/Forecasting/data/reg.xlsx", sheet = "chin_reg")
france_reg <- read_excel("D:/Google Drive/Library/Forecasting/data/reg.xlsx", sheet = "france_reg")
italy_reg <- read_excel("D:/Google Drive/Library/Forecasting/data/reg.xlsx", sheet = "italy_reg")
japan_reg <- read_excel("D:/Google Drive/Library/Forecasting/data/reg.xlsx", sheet = "japan_reg")
sk_reg <- read_excel("D:/Google Drive/Library/Forecasting/data/reg.xlsx", sheet = "sk_reg")

###start data when first death occurs
usa_reg <- usa_reg %>% filter(y != 0)
usa_reg$x = seq(1:nrow(usa_reg))
china_reg <- china_reg %>% filter(y != 0)
china_reg$x = seq(1:nrow(china_reg))
france_reg <- france_reg %>% filter(y != 0)
france_reg$x = seq(1:nrow(france_reg))
italy_reg <- italy_reg %>% filter(y != 0)
italy_reg$x = seq(1:nrow(italy_reg))
japan_reg <- japan_reg %>% filter(y != 0)
japan_reg$x = seq(1:nrow(japan_reg))
sk_reg <- sk_reg %>% filter(y != 0)
sk_reg$x = seq(1:nrow(sk_reg))
